# Generated by Django 5.1.1 on 2024-09-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
