# Generated by Django 5.1.1 on 2024-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
