# Generated by Django 5.1.1 on 2024-09-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_services_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
