# Generated by Django 5.1.1 on 2024-09-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'Users Information'},
        ),
        migrations.AddField(
            model_name='user',
            name='suscribed',
            field=models.BooleanField(default=True),
        ),
    ]
